import Head from 'next/head'
import Link from 'next/link'
import Header from '../../../components/Header'
import styles from '../../../styles/Home.module.css'
import useTranslation from 'next-translate/useTranslation'

export const getStaticPaths = async () => {
    return {
      paths: [],
      fallback: 'blocking',
    }
  }

export async function getStaticProps({params}) {
  const { site } =  params

  return {
      props: {
        site,
      },
  }
}

export default function Inner({ site }) {
  const { t, lang } = useTranslation('common')
  const example = t('title')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
          {example}
        </h1>

        <div className={styles.grid}>
          <Link href="/">
            <a className={styles.card}>
              <h2>Index page &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>
    </div>
  )
}
